CREATE USER IF NOT EXISTS 'vradmin'@'localhost' IDENTIFIED BY 'vradmin';
GRANT ALL PRIVILEGES ON * . * TO 'vradmin'@'localhost';
CREATE DATABASE IF NOT EXISTS colegio;
USE colegio;
CREATE TABLE ALUMNO 
(
DNI VARCHAR(10) NOT NULL, 
  NOMBRE VARCHAR(20) NOT NULL, 
  APELLIDO1 VARCHAR(20), 
  APELLIDO2 VARCHAR(20), 
  TELEFONO INT(10), 
  FECHANACIMIENTO DATE,
  PRIMARY KEY (DNI)
);

CREATE TABLE CICLO 
(

 ID INT NOT NULL AUTO_INCREMENT ,
  NOMBRE VARCHAR(20) NOT NULL, 
  NIVEL varchar(25), 
  CURSOS int(1),
  PRIMARY KEY (ID)
);
CREATE TABLE MODULO 
(
 ID INT NOT NULL AUTO_INCREMENT ,
  NOMBRE VARCHAR(20) NOT NULL, 
  CURSO INT(1), 
  HORAS INT(5), 
  IDCICLO INT , 
PRIMARY KEY (ID,IDCICLO)
);


CREATE TABLE CURSA 
(
 IDMODULO INT NOT NULL AUTO_INCREMENT ,
  ANHO VARCHAR(10) NOT NULL, 
  NOTA DECIMAL(6,2), 
  DNI VARCHAR(10), 
	PRIMARY KEY (IDMODULO,DNI)
);